// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';import{afterEach,beforeAll,describe,expect,it}from'vitest';import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';import{MemoryRouter}from'react-router-dom';
import{ContentRenderer}from'../src/app/ContentRenderer.js';import CpuInstructionCycle from'../src/app/interactive/diagrams/CpuInstructionCycle.js';import CpuGpuParallelism from'../src/app/interactive/diagrams/CpuGpuParallelism.js';import NpuMacDataflow from'../src/app/interactive/diagrams/NpuMacDataflow.js';import SocBlockMap from'../src/app/interactive/diagrams/SocBlockMap.js';import MemoryCellComparison from'../src/app/interactive/diagrams/MemoryCellComparison.js';import MemoryHierarchyBottleneck from'../src/app/interactive/diagrams/MemoryHierarchyBottleneck.js';import PpaTradeoff from'../src/app/interactive/diagrams/PpaTradeoff.js';import FinfetGaa from'../src/app/interactive/diagrams/FinfetGaa.js';import PhotoEtchPatternTransfer from'../src/app/interactive/diagrams/PhotoEtchPatternTransfer.js';import BacksidePowerDelivery from'../src/app/interactive/diagrams/BacksidePowerDelivery.js';import{interactiveRegistry,registeredInteractive}from'../src/app/interactive/registry.js';import{parseContentDirectory}from'../src/content/parse.js';import{createContentIndex}from'../src/content/write.js';import type{ContentCatalog,ContentIndex,InteractiveDeclaration}from'../src/content/types.js';
const declaration:InteractiveDeclaration={instanceId:'m45:1',documentId:'m04-l01',type:'cpu-instruction-cycle',attributes:{type:'cpu-instruction-cycle'},original:{markdown:'',source:{path:'fixture.md',start:0,end:0,startLine:1,endLine:1}}};const props={declaration,documentRevision:'r1'};const feedback=()=>document.querySelector('.interactive-feedback')!;const choose=(name:string)=>fireEvent.click(screen.getByRole('radio',{name}));afterEach(cleanup);
describe('Module 4 and 5 educational interactions',()=>{
it('moves 2 + 3 through fetch, decode, execute and store',()=>{render(<CpuInstructionCycle {...props}/>);expect(feedback()).toHaveTextContent('Memory');fireEvent.click(screen.getByRole('button',{name:'Decode'}));expect(feedback()).toHaveTextContent('R1=2');fireEvent.click(screen.getByRole('button',{name:'Execute'}));expect(feedback()).toHaveTextContent('결과 5');fireEvent.click(screen.getByRole('button',{name:'Store'}));expect(feedback()).toHaveTextContent('R3');expect(screen.getByText(/한 clock/)).toBeInTheDocument()});
it('limits parallelism when tasks depend on previous results',()=>{render(<CpuGpuParallelism {...props}/>);choose('많은 단순 작업자');expect(feedback()).toHaveTextContent('8개를 동시에');choose('의존 작업 8개');expect(feedback()).toHaveTextContent('실행 가능한 작업은 1개')});
it('shows multiply, accumulation and reduced movement with reuse',()=>{render(<NpuMacDataflow {...props}/>);expect(feedback()).toHaveTextContent('2 × 가중치 3 = 6');fireEvent.click(screen.getByRole('button',{name:'누산 1'}));expect(feedback()).toHaveTextContent('부분합');fireEvent.click(screen.getByRole('button',{name:'출력'}));expect(feedback()).toHaveTextContent('출력 10');choose('가까이 재사용');expect(feedback()).toHaveTextContent('반복 이동을 줄입니다')});
it('changes participating SoC blocks for product tasks',()=>{render(<SocBlockMap {...props}/>);choose('사진 처리');expect(feedback()).toHaveTextContent('GPU');choose('AI 추론');expect(feedback()).toHaveTextContent('NPU');choose('화면 출력');expect(feedback()).toHaveTextContent('Display')});
it('distinguishes SRAM, DRAM and NAND cell retention',()=>{render(<MemoryCellComparison {...props}/>);expect(feedback()).toHaveTextContent('feedback');choose('DRAM');expect(feedback()).toHaveTextContent('refresh');choose('전원 OFF');expect(feedback()).toHaveTextContent('보장하지 않습니다');choose('NAND Flash');expect(feedback()).toHaveTextContent('비휘발성')});
it('reduces movement burden through bandwidth, reuse and overlap',()=>{render(<MemoryHierarchyBottleneck {...props}/>);expect(feedback()).toHaveTextContent('계산보다 큰 병목');const highs=screen.getAllByRole('radio',{name:'큼 / 높음'});fireEvent.click(highs[1]!);const ons=screen.getAllByRole('radio',{name:'있음'});fireEvent.click(ons[0]!);fireEvent.click(ons[1]!);expect(feedback()).toHaveTextContent('상대적으로 줄어든');expect(screen.getByText(/latency와 같은 개념이 아닙니다/)).toBeInTheDocument()});
it('shows PPA tradeoffs without inventing an optimum score',()=>{render(<PpaTradeoff {...props}/>);choose('성능 우선');expect(feedback()).toHaveTextContent('전력·면적 부담');choose('면적 우선');expect(feedback()).toHaveTextContent('성능이 제한');expect(screen.getByText(/C × V² × f/)).toBeInTheDocument()});
it('compares gate wrapping while preserving oxide and package boundaries',()=>{render(<FinfetGaa {...props}/>);expect(feedback()).toHaveTextContent('한 면');choose('FinFET');expect(feedback()).toHaveTextContent('위와 양옆');choose('GAA · Nanosheet');expect(feedback()).toHaveTextContent('더 넓게 감싸');expect(screen.getByText(/여러 Die를 쌓는 패키징/)).toBeInTheDocument()});
it('keeps PR formation separate from Etch transfer at smaller pitch',()=>{render(<PhotoEtchPatternTransfer {...props}/>);choose('상대적으로 작은 Pitch');expect(feedback()).toHaveTextContent('공정 창 관리');fireEvent.click(screen.getByRole('button',{name:'PR Pattern'}));expect(feedback()).toHaveTextContent('Film은 아직 제거되지 않았습니다');fireEvent.click(screen.getByRole('button',{name:'Etch Transfer'}));expect(feedback()).toHaveTextContent('아래 Film')});
it('moves only the power path to the backside',()=>{render(<BacksidePowerDelivery {...props}/>);expect(feedback()).toHaveTextContent('Signal과 Power');choose('Backside power');expect(feedback()).toHaveTextContent('Signal은 전면');choose('Power 보기');expect(screen.getByText(/모든 배선을 뒤로 보내는 구조가 아니며/)).toBeInTheDocument()});
});
describe('real Module 4 and 5 slots',()=>{let catalog:ContentCatalog;let index:ContentIndex;beforeAll(async()=>{const parsed=await parseContentDirectory('content');if(!parsed.ok)throw new Error(JSON.stringify(parsed.diagnostics));catalog=parsed.data;index=createContentIndex(catalog)});it.each(['m04-l01','m04-l02','m04-l03','m04-l04','m04-l05','m04-l06','m05-l01','m05-l02','m05-l03','m05-l04'])('renders the registered slot in %s',async id=>{const document=catalog.documentsById[id]!;const blocks=document.body.blocks.filter(b=>b.kind==='interactive');expect(blocks).toHaveLength(1);expect(registeredInteractive(interactiveRegistry,blocks[0]!.value.type)).toBeDefined();const view=render(<MemoryRouter><ContentRenderer document={document} index={index}/></MemoryRouter>);await waitFor(()=>expect(view.container.querySelectorAll('.interactive-diagram')).toHaveLength(1));expect(view.container.querySelector('.interactive-placeholder')).toBeNull()})});
