import { useState } from 'react'; import { DiagramFrame } from '../DiagramFrame.js'; import { StructureChoices } from '../primitives/StructureView.js'; import { ProcessExplanation, ProcessView } from '../primitives/ProcessView.js'; import type { InteractiveProps } from '../types.js';
const contaminants=[{value:'particle',label:'Particle'},{value:'organic',label:'Organic'},{value:'metal',label:'Metal contamination'},{value:'residue',label:'공정 잔사'}] as const;const strengths=[{value:'weak',label:'부족'},{value:'proper',label:'적정'},{value:'strong',label:'과도'}] as const;
export default function Clean(_props:InteractiveProps){const [kind,setKind]=useState<typeof contaminants[number]['value']>('particle');const [strength,setStrength]=useState<'weak'|'proper'|'strong'>('proper');const label=contaminants.find(x=>x.value===kind)!.label;const feedback=strength==='weak'?`${label} 일부가 남아 다음 공정과 전기 특성에 영향을 줄 수 있습니다.`:strength==='proper'?`${label}을 제거하면서 필요한 표면 구조를 보존하는 균형 사례입니다.`:`오염 제거는 커지지만 필요한 Film이나 표면까지 손상할 수 있는 과도 조건 사례입니다.`;const remaining=strength==='weak'?7:strength==='proper'?1:0;
return <DiagramFrame title="Clean과 표면 보존" objective="오염 종류와 세정 강도 사례를 골라 제거와 구조 보존의 균형을 확인하세요." controls={<div className="process-controls"><StructureChoices label="제거 대상" value={kind} options={contaminants} onChange={setKind}/><StructureChoices label="세정 정도" value={strength} options={strengths} onChange={setStrength}/></div>} feedback={feedback} takeaway="Clean은 공정 사이에서 반복되며, 불필요한 오염·잔류물을 제거하면서 필요한 구조는 보존해야 한다." onReset={()=>{setKind('particle');setStrength('proper')}}>
<div className="process-layout"><ProcessView title="세정 후 표면" description={feedback}>
 <path className={`clean-surface ${strength}`} d={strength==='strong'?'M35 175 Q90 145 145 175 T255 175 T385 175 V245 H35 Z':'M35 165 H385 V245 H35 Z'}/>{Array.from({length:remaining},(_,i)=><g className={`clean-contaminant ${kind}`} key={i}><circle cx={65+i*45} cy={145-(i%2)*12} r="9"/><text x={65+i*45} y={149-(i%2)*12} textAnchor="middle">{kind==='particle'?'P':kind==='organic'?'O':kind==='metal'?'M':'R'}</text></g>)}
 <text x="210" y="275" textAnchor="middle">{strength==='strong'?'필요한 표면 손상 사례':'보존할 구조'}</text>
</ProcessView><ProcessExplanation heading={`${label} · ${strengths.find(x=>x.value===strength)!.label}`}><p>{feedback}</p><p>Etch는 구조를 만들기 위해 재료를 의도적으로 가공하고, Clean은 불필요한 오염과 잔사를 제거합니다.</p></ProcessExplanation></div>
</DiagramFrame>}
