import { useState } from 'react'; import { DiagramFrame } from '../DiagramFrame.js'; import { StructureChoices } from '../primitives/StructureView.js'; import { ProcessExplanation, ProcessView } from '../primitives/ProcessView.js'; import type { InteractiveProps } from '../types.js';
const methods=[{value:'pvd',label:'PVD'},{value:'cvd',label:'CVD'},{value:'ald',label:'ALD'}] as const;const shapes=[{value:'flat',label:'평탄면'},{value:'trench',label:'단차 / Trench'}] as const;
const data={pvd:{top:'두꺼움',side:'얇음',bottom:'상대적으로 적음',note:'방향성이 큰 입사로 윗면 피복이 두드러지는 대표 사례'},cvd:{top:'고름',side:'비교적 고름',bottom:'비교적 고름',note:'기체 반응으로 단차를 비교적 고르게 덮는 대표 사례'},ald:{top:'고름',side:'고름',bottom:'고름',note:'자기 제한적 표면 반응을 반복해 높은 Conformality를 얻는 대표 사례'}} as const;
export default function DepositionConformality(_props:InteractiveProps){const [method,setMethod]=useState<keyof typeof data>('pvd');const [shape,setShape]=useState<'flat'|'trench'>('trench');const d=data[method];const feedback=`${method.toUpperCase()} · ${shape==='flat'?'평탄면':'단차'}: ${d.note}.`;
return <DiagramFrame title="증착과 단차 피복" objective="증착 방식과 표면 형상을 골라 위·옆·바닥의 상대 피복을 비교하세요." controls={<div className="process-controls"><StructureChoices label="증착 방식" value={method} options={methods} onChange={setMethod}/><StructureChoices label="표면 형상" value={shape} options={shapes} onChange={setShape}/></div>} feedback={feedback} takeaway="막 형성 방식에 따라 단차의 위·옆·바닥 피복 정도가 달라진다." onReset={()=>{setMethod('pvd');setShape('trench')}}>
<div className="process-layout"><ProcessView title={`${method.toUpperCase()} 피복 개념도`} description={feedback}>
 <path className="process-substrate-profile" d={shape==='flat'?'M35 190 H385 V245 H35 Z':'M35 125 H145 V215 H275 V125 H385 V245 H35 Z'}/>
 <path className={`process-deposit ${method}`} d={shape==='flat'?'M35 175 H385':'M35 110 H160 V195 H260 V110 H385'}/><text x="210" y="270" textAnchor="middle">대표 정성 단면</text>
</ProcessView><ProcessExplanation heading={`${method.toUpperCase()} 상대 피복`}><dl className="process-values"><div><dt>윗면</dt><dd>{d.top}</dd></div><div><dt>옆면</dt><dd>{d.side}</dd></div><div><dt>바닥</dt><dd>{d.bottom}</dd></div></dl><p>{d.note}</p></ProcessExplanation></div><p className="process-note">실제 피복은 재료·구조·조건에 따라 달라집니다. ALD 한 cycle이 언제나 정확히 원자 한 층을 뜻하지 않습니다.</p>
</DiagramFrame>}
