import { useState } from 'react'; import { DiagramFrame } from '../DiagramFrame.js'; import { StructureChoices } from '../primitives/StructureView.js'; import { ProcessExplanation, ProcessView } from '../primitives/ProcessView.js'; import type { InteractiveProps } from '../types.js';
const levels=[{value:'low',label:'낮음'},{value:'high',label:'높음'}] as const;const masks=[{value:'masked',label:'Mask 사용'},{value:'open',label:'전체 노출'}] as const;
export default function ImplantProfile(_props:InteractiveProps){const [energy,setEnergy]=useState<'low'|'high'>('low');const [dose,setDose]=useState<'low'|'high'>('low');const [mask,setMask]=useState<'masked'|'open'>('masked');const depth=energy==='low'?'얕은 쪽':'깊은 쪽';const amount=dose==='low'?'상대적으로 적음':'상대적으로 많음';const feedback=`Energy가 ${energy==='low'?'낮아':'높아'} 분포 중심은 ${depth}, Dose가 ${dose==='low'?'낮아':'높아'} 주입량은 ${amount}입니다. ${mask==='masked'?'Mask 아래 영역은 주입을 막습니다.':'표면 전체가 노출됩니다.'}`;
const dots=Array.from({length:dose==='low'?8:20},(_,i)=>({x:55+(i*47)%310,y:(energy==='low'?135:170)+(i%4)*12}));
return <DiagramFrame title="Ion Implant 분포" objective="Energy, Dose와 Mask를 바꾸며 깊이·양·선택 영역을 구분하세요." controls={<div className="process-controls"><StructureChoices label="Energy · 깊이에 영향" value={energy} options={levels} onChange={setEnergy}/><StructureChoices label="Dose · 양에 영향" value={dose} options={levels} onChange={setDose}/><StructureChoices label="선택 영역" value={mask} options={masks} onChange={setMask}/></div>} feedback={feedback} takeaway="Implant의 Energy는 주로 깊이, Dose는 주입량에 영향을 주며, 주입과 전기적 활성화는 같은 단계가 아니다." onReset={()=>{setEnergy('low');setDose('low');setMask('masked')}}>
<div className="process-layout"><ProcessView title="도펀트 상대 분포" description={feedback}>
 <rect className="implant-silicon" x="35" y="100" width="350" height="155"/>{mask==='masked'&&<rect className="implant-mask" x="35" y="72" width="150" height="28"/>}
 {dots.filter(d=>mask==='open'||d.x>195).map((d,i)=><circle className="implant-dot" key={i} cx={d.x} cy={d.y} r={dose==='high'?6:5}/>)}
 <path className="implant-arrows" d="M75 25 V65 M155 25 V65 M235 25 V65 M315 25 V65"/><text x="210" y="280" textAnchor="middle">상대 분포 · 실제 recipe 수치 아님</text>
</ProcessView><ProcessExplanation heading="현재 조건"><dl className="process-values"><div><dt>분포 중심</dt><dd>{depth}</dd></div><div><dt>주입량</dt><dd>{amount}</dd></div><div><dt>영역</dt><dd>{mask==='masked'?'선택 주입':'전체 노출'}</dd></div></dl><p>주입 직후에는 결정 손상이 있을 수 있으며 별도 Anneal로 회복·활성화를 돕습니다.</p></ProcessExplanation></div>
</DiagramFrame>}
