import { useState } from 'react'; import { DiagramFrame } from '../DiagramFrame.js'; import { StructureChoices } from '../primitives/StructureView.js'; import { ProcessExplanation, ProcessStepControls, ProcessView, type ProcessStep } from '../primitives/ProcessView.js'; import type { InteractiveProps } from '../types.js';
const flows={film:{label:'패턴이 있는 Film',steps:[['Film 준비','증착·산화 등으로 가공 대상 막을 준비합니다.'],['PR 패턴','Photo로 처리할 위치를 정합니다.'],['선택 제거','Etch로 열린 곳의 Film을 제거합니다.'],['마무리','PR 제거와 Clean으로 다음 단계를 준비합니다.']]},doping:{label:'선택 도핑 영역',steps:[['Mask 준비','Photo로 주입할 위치를 엽니다.'],['도펀트 주입','Implant로 Energy와 Dose를 관리합니다.'],['열처리','손상 회복·활성화와 확산을 관리합니다.'],['확인 · Clean','목표 분포와 표면 상태를 확인합니다.']]},wire:{label:'금속 배선 · Via',steps:[['절연막 준비','배선을 둘러쌀 절연막을 형성합니다.'],['공간 형성','Photo와 Etch로 Line·Via 공간을 만듭니다.'],['금속 채움','필요한 Barrier와 금속을 형성해 공간을 채웁니다.'],['CMP · Clean','표면 과잉 금속과 잔류물을 제거합니다.']]}} as const;
const options=Object.entries(flows).map(([value,x])=>({value:value as keyof typeof flows,label:x.label}));
export default function ProcessIntegrationReview(_props:InteractiveProps){const [goal,setGoal]=useState<keyof typeof flows>('film');const [step,setStep]=useState(0);const flow=flows[goal];const steps:readonly ProcessStep[]=flow.steps.map(([label,detail])=>({label,detail}));const choose=(v:keyof typeof flows)=>{setGoal(v);setStep(0)};const s=steps[step]!;
return <DiagramFrame title="공정 통합 복습" objective="만들 구조를 먼저 고르고, 각 작업이 필요한 이유와 구조 변화를 단계별로 연결하세요." controls={<div className="process-controls"><StructureChoices label="구조 목표" value={goal} options={options} onChange={choose}/><ProcessStepControls steps={steps} index={step} onChange={setStep}/></div>} feedback={`${s.label}: ${s.detail}`} takeaway="공정 이름의 고정 순서를 외우기보다, 목표 구조에 필요한 형성·선택·제거·연결·평탄화·세정을 연결한다." onReset={()=>{setGoal('film');setStep(0)}}>
<div className="process-layout"><ProcessView title={`${flow.label} · ${s.label}`} description={s.detail}>
 {steps.map((x,i)=><g key={x.label} className={`integration-node ${i===step?'selected':''}`} transform={`translate(${60+i*100} 135)`}><circle r="32"/><text textAnchor="middle" y="5">{i+1}</text>{i<steps.length-1&&<path d="M34 0 H66"/>}<text className="integration-label" textAnchor="middle" y="58">{x.label}</text></g>)}
</ProcessView><ProcessExplanation heading={`${step+1}. ${s.label}`}><p>{s.detail}</p><p>이 흐름은 원리를 연결한 교육 예입니다. 실제 세부 순서는 구조·재료·공정에 따라 달라집니다.</p></ProcessExplanation></div>
</DiagramFrame>}
