import { useId, useReducer } from 'react';
import { DiagramFrame } from '../DiagramFrame.js';
import type { Bit } from '../primitives/BinaryToggle.js';
import type { InteractiveProps } from '../types.js';

type Operation='hold'|'write0'|'write1'|'read';
type State={q:Bit;operation:Operation;step:number};
type Action={type:'select';operation:Operation}|{type:'next'}|{type:'reset'};
const STEPS={hold:['WL OFF · 저장 유지'],write0:['BL=0 / BLB=1 준비','WL ON · Cell 연결','Q에 0 쓰기','WL OFF · Hold'],write1:['BL=1 / BLB=0 준비','WL ON · Cell 연결','Q에 1 쓰기','WL OFF · Hold'],read:['BL/BLB 같은 상태로 precharge','WL ON · Cell 연결','저장값에 따른 작은 차이','Read 결과 확인','WL OFF · Hold']} as const;
function reducer(state:State,action:Action):State { if(action.type==='reset')return{q:0,operation:'hold',step:0}; if(action.type==='select')return{...state,operation:action.operation,step:0}; const max=STEPS[state.operation].length-1; const next=Math.min(max,state.step+1); const writes=state.operation==='write0'||state.operation==='write1'; return{...state,q:writes&&next>=2?(state.operation==='write1'?1:0):state.q,step:next}; }

export default function SramCell(_props:InteractiveProps){
  const [state,dispatch]=useReducer(reducer,{q:0,operation:'hold',step:0}); const qbar=(1-state.q) as Bit; const titleId=useId(),descId=useId(); const steps=STEPS[state.operation]; const done=state.step===steps.length-1;
  const lineState=state.operation==='write0'?'BL 0 · BLB 1':state.operation==='write1'?'BL 1 · BLB 0':state.operation==='read'?(state.step===0?'BL = BLB · precharge':state.step>=2?`작은 차이 → 저장 ${state.q}`:'BL/BLB 연결'):'Cell과 분리';
  const feedback=state.operation==='hold'?`Hold: WL이 꺼져 Q=${state.q}, Q̅=${qbar} 상태를 유지합니다.`:`${steps[state.step]} — Q=${state.q}, Q̅=${qbar}. ${state.operation==='read'?'읽기는 저장 bit를 바꾸지 않습니다.':''}`;
  return <DiagramFrame title="6T SRAM Cell" objective="Hold·Write·Read 단계에서 Q/Q̅와 WL·BL/BLB의 역할을 확인하세요." controls={<div className="batch-controls"><div className="segmented-control sram-modes" role="group" aria-label="SRAM 동작">{(['hold','write0','write1','read'] as const).map(op=><button key={op} type="button" aria-pressed={state.operation===op} onClick={()=>dispatch({type:'select',operation:op})}>{op==='hold'?'Hold':op==='write0'?'Write 0':op==='write1'?'Write 1':'Read'}</button>)}</div><button className="step-button" type="button" disabled={done} onClick={()=>dispatch({type:'next'})}>다음 단계</button></div>} feedback={feedback} takeaway="6T SRAM은 교차 연결 inverter 2개와 access transistor 2개로 전원이 있는 동안 1 bit를 저장한다." onReset={()=>dispatch({type:'reset'})}>
    <div className="sram-layout"><ol className="step-list" aria-label="현재 동작 단계">{steps.map((step,i)=><li key={step} aria-current={i===state.step?'step':undefined}>{step}</li>)}</ol><svg viewBox="0 0 720 390" role="img" aria-labelledby={`${titleId} ${descId}`}><title id={titleId}>6T SRAM {state.operation}, Q {state.q}, Q bar {qbar}</title><desc id={descId}>{feedback} 6T는 6 bit가 아니라 transistor 6개를 뜻합니다.</desc><text className="rail-label" x="100" y="35">BL</text><text className="rail-label" x="620" y="35">BLB</text><path className="bitline" d="M100 50 V340 M620 50 V340"/><path className={`wordline ${state.operation==='hold'?'':'active'}`} d="M55 95 H665"/><text x="360" y="82" textAnchor="middle">WL · {state.operation==='hold'||state.step===0?'OFF':'ON'}</text><g className="access-transistor"><rect x="80" y="115" width="95" height="55" rx="10"/><text x="128" y="148" textAnchor="middle">Access T</text><rect x="545" y="115" width="95" height="55" rx="10"/><text x="592" y="148" textAnchor="middle">Access T</text></g><path className="concept-wire" d="M175 143 H235 M485 143 H545"/><g className="sram-inverter"><rect x="235" y="105" width="115" height="115" rx="16"/><text x="292" y="145" textAnchor="middle">Inverter A</text><text x="292" y="180" textAnchor="middle">2T</text><rect x="370" y="105" width="115" height="115" rx="16"/><text x="428" y="145" textAnchor="middle">Inverter B</text><text x="428" y="180" textAnchor="middle">2T</text></g><path className="feedback-wire" d="M350 135 C390 55 470 55 485 135 M370 190 C330 270 250 270 235 190"/><circle className={`storage-node q${state.q}`} cx="235" cy="255" r="42"/><text x="235" y="250" textAnchor="middle">Q</text><text x="235" y="280" textAnchor="middle">{state.q}</text><circle className={`storage-node q${qbar}`} cx="485" cy="255" r="42"/><text x="485" y="250" textAnchor="middle">Q̅</text><text x="485" y="280" textAnchor="middle">{qbar}</text><text className="concept-value" x="360" y="345" textAnchor="middle">{lineState}</text></svg><div className="result-strip"><strong>저장된 1 bit: {state.q}</strong><span>Q={state.q} · Q̅={qbar} · 4T 유지 + 2T 접근 = 6T</span><small>읽기 전 BL/BLB는 같은 상태에서 시작하며, 읽기 차이는 정성적으로만 표시합니다.</small></div></div>
  </DiagramFrame>;
}
