import { lazy } from 'react';

import type { InteractiveRegistry } from './types.js';

export const interactiveRegistry: InteractiveRegistry = Object.freeze({
  'cmos-inverter': lazy(() => import('./diagrams/CmosInverter.js')),
  'wafer-die-transistor': lazy(() => import('./diagrams/WaferDieTransistor.js')),
  'voltage-current': lazy(() => import('./diagrams/VoltageCurrent.js')),
  'mosfet-channel': lazy(() => import('./diagrams/MosfetChannel.js')),
  'nmos-pmos-channel': lazy(() => import('./diagrams/NmosPmosChannel.js')),
  'rc-coupling': lazy(() => import('./diagrams/RcCoupling.js')),
  'mos-capacitor': lazy(() => import('./diagrams/MosCapacitor.js')),
  'np-doping': lazy(() => import('./diagrams/NpDoping.js')),
  'nand-nor': lazy(() => import('./diagrams/NandNor.js')),
  'half-adder': lazy(() => import('./diagrams/HalfAdder.js')),
  'full-adder': lazy(() => import('./diagrams/FullAdder.js')),
  'flipflop-register': lazy(() => import('./diagrams/FlipflopRegister.js')),
  'sram-cell': lazy(() => import('./diagrams/SramCell.js')),
  'die-floorplan': lazy(() => import('./diagrams/DieFloorplan.js')),
  'feol-mol-beol': lazy(() => import('./diagrams/FeolMolBeol.js')),
  'signal-clock-pdn': lazy(() => import('./diagrams/SignalClockPdn.js')),
  'pad-bump-package-pcb': lazy(() => import('./diagrams/PadBumpPackagePcb.js')),
  'chiplet-package': lazy(() => import('./diagrams/ChipletPackage.js')),
  'wafer-shot-reticle': lazy(() => import('./diagrams/WaferShotReticle.js')),
  'process-overview': lazy(() => import('./diagrams/ProcessOverview.js')),
  'photo-pattern-transfer': lazy(() => import('./diagrams/PhotoPatternTransfer.js')),
  'etch-profile': lazy(() => import('./diagrams/EtchProfile.js')),
  'deposition-conformality': lazy(() => import('./diagrams/DepositionConformality.js')),
  'dual-damascene': lazy(() => import('./diagrams/DualDamascene.js')),
  'cmp': lazy(() => import('./diagrams/Cmp.js')),
  'implant-profile': lazy(() => import('./diagrams/ImplantProfile.js')),
  'thermal-process': lazy(() => import('./diagrams/ThermalProcess.js')),
  'clean': lazy(() => import('./diagrams/Clean.js')),
  'process-integration-review': lazy(() => import('./diagrams/ProcessIntegrationReview.js')),
  'cpu-instruction-cycle': lazy(() => import('./diagrams/CpuInstructionCycle.js')),
  'cpu-gpu-parallelism': lazy(() => import('./diagrams/CpuGpuParallelism.js')),
  'npu-mac-dataflow': lazy(() => import('./diagrams/NpuMacDataflow.js')),
  'soc-block-map': lazy(() => import('./diagrams/SocBlockMap.js')),
  'memory-cell-comparison': lazy(() => import('./diagrams/MemoryCellComparison.js')),
  'memory-hierarchy-bottleneck': lazy(() => import('./diagrams/MemoryHierarchyBottleneck.js')),
  'ppa-tradeoff': lazy(() => import('./diagrams/PpaTradeoff.js')),
  'finfet-gaa': lazy(() => import('./diagrams/FinfetGaa.js')),
  'photo-etch-pattern-transfer': lazy(() => import('./diagrams/PhotoEtchPatternTransfer.js')),
  'backside-power-delivery': lazy(() => import('./diagrams/BacksidePowerDelivery.js')),
  'tsv-bonding': lazy(() => import('./diagrams/TsvBonding.js')),
  'package-yield-path': lazy(() => import('./diagrams/PackageYieldPath.js')),
  'hbm-bandwidth': lazy(() => import('./diagrams/HbmBandwidth.js')),
  'hbm-stack': lazy(() => import('./diagrams/HbmStack.js')),
  'hbm-capacity-vs-bandwidth': lazy(() => import('./diagrams/HbmCapacityVsBandwidth.js')),
  'hbm-test-thermal': lazy(() => import('./diagrams/HbmTestThermal.js')),
  'semiconductor-ecosystem': lazy(() => import('./diagrams/SemiconductorEcosystem.js')),
  'pdk-eda-ip': lazy(() => import('./diagrams/PdkEdaIp.js')),
  'design-to-silicon': lazy(() => import('./diagrams/DesignToSilicon.js')),
  'yield-capacity-cost': lazy(() => import('./diagrams/YieldCapacityCost.js')),
  'technology-maturity-map': lazy(() => import('./diagrams/TechnologyMaturityMap.js')),
  'high-na-process-window': lazy(() => import('./diagrams/HighNaProcessWindow.js')),
  'hbm-spec-reader': lazy(() => import('./diagrams/HbmSpecReader.js')),
  'chiplet-interoperability': lazy(() => import('./diagrams/ChipletInteroperability.js')),
});

export function registeredInteractive(registry: InteractiveRegistry, type: string) {
  return Object.hasOwn(registry, type) ? registry[type] : undefined;
}
